function Hd = fittroNotrch
%FITTRONOTRCH Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.8 and the Signal Processing Toolbox 6.11.
%
% Generated on: 01-Nov-2016 17:37:12
%

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 8192;  % Sampling Frequency

Fnotch = 60;   % Notch Frequency
BW     = 0.1;  % Bandwidth
Apass  = 1;    % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
